#!/usr/bin/env bash
if [[ ! -d env ]]; then
   python3.9 -m virtualenv env 
fi
rm -rf dist/ build/ *.egg-info target/ classes/
direnv allow
./scripts/compile-library
cp target/*.so metal/
env/bin/python3 -m pip install build
env/bin/python3 -m build



